<?xml version="1.0" standalone="yes"?>
<!DOCTYPE entity [
	
  <!ELEMENT entity        (operacion*)>
  <!ELEMENT operacion     (input* , output* , dataset* , tables*, transformer?, forms)>
  
  <!ELEMENT input		  (campoEntrada*)>	<!--   Es la entrada de la operacion. Lo definido aquí llegará en un mapa a la operacion -->
  <!ELEMENT forms		  (form*)>		  	<!--   Para definir una restriccion y conocer que clients utilizan esta operacion. Es a modo de mantenimiento, por ejemplo: al cambiar una operacion, se debe saber quienes suelen llamar a la operacion para realizar los debidos cambios -->
  <!ELEMENT output		  (campoSalida*)> 	<!--   Define el formato de salida -->
  <!ELEMENT transformer	  EMPTY>			<!--   Define una clase que es la encargada de mostrar los resultados en la salida de la operacion. (Muchas tablas, una sola, en paralelo) -->


  <!ELEMENT campoEntrada  (input*|campoEntrada*)>  
  <!ELEMENT campoSalida   (campoSalida*,output*)>  
  
  <!ELEMENT dataset       (campo*)>
  <!ELEMENT campo         EMPTY>
  <!ELEMENT tables       (tableDef+)>
  <!ELEMENT tableDef     (campoTable*)>
  <!ELEMENT campoTable   EMPTY>
  
  <!ATTLIST transformer clase           CDATA #REQUIRED>
  
  <!ATTLIST form name	CDATA #REQUIRED>
  
  <!ATTLIST input name           	 	CDATA    #IMPLIED><!--   Nombre que se corresponde con la entrada de delphi. Si en delphi mandan el valor Name, acá debe exstir en valor Name para obtener los demas datos -->
  <!ATTLIST input keyName           	CDATA    #IMPLIED><!--   Indica el key del mapa que llega a la operacion. Si el valor es 'leo', se debera recuperar usando la key 'leo' sobre el mapa en la operacion -->
  <!ATTLIST input clase           	 	CDATA    #IMPLIED><!-- 	define la clase del parmetro recibido -->
  <!ATTLIST input fieldID           	CDATA    #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
  <!ATTLIST input nombreEntidad        	CDATA    #IMPLIED>
  
  <!ATTLIST campoEntrada name			CDATA #IMPLIED>
  <!ATTLIST campoEntrada clase			CDATA #IMPLIED>
  <!ATTLIST campoEntrada nombreEntidad	CDATA #IMPLIED>
  <!ATTLIST campoEntrada metodo			CDATA #IMPLIED>
  <!ATTLIST campoEntrada fieldID        CDATA    #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
 
  <!ATTLIST output name					CDATA #REQUIRED> 
  <!ATTLIST output tableName           	CDATA #REQUIRED><!-- va a representar el nombre de la tabla -->

  <!ATTLIST campoSalida tableName		CDATA #IMPLIED> <!-- en caso de ser hijo de otro campoSalida, es una tabla, y este campo tendra el nombre de la tabla -->
  <!ATTLIST campoSalida target			CDATA #IMPLIED> <!-- El nombre del metodo para recuperar los datos -->
  <!ATTLIST campoSalida value			CDATA #IMPLIED> <!-- el valor de la columna que contendra el valor de resltado de target -->

  <!ATTLIST operacion name              ID    #REQUIRED>
  <!ATTLIST operacion clase             CDATA #IMPLIED>
  <!ATTLIST operacion entidad           CDATA #IMPLIED>
  <!ATTLIST operacion XMLWriter         CDATA #IMPLIED>
  <!ATTLIST operacion redirect          CDATA #IMPLIED>
  <!ATTLIST operacion usaJMS            CDATA #IMPLIED>
  
  <!ATTLIST dataset name                CDATA #REQUIRED>
  <!ATTLIST dataset value               CDATA #IMPLIED>
  <!ATTLIST dataset tabla               CDATA #IMPLIED>
  
  <!ATTLIST campo   name                CDATA #REQUIRED>
  <!ATTLIST campo   value               CDATA #IMPLIED>
  
  <!ATTLIST tableDef    name           	CDATA #REQUIRED>

  <!ATTLIST campoTable	name        	CDATA #REQUIRED>
  <!ATTLIST campoTable  orden       	CDATA #IMPLIED>
  <!ATTLIST campoTable  tipo        	CDATA #IMPLIED>
  <!ATTLIST campoTable  longitud    	CDATA #IMPLIED>
  
]>

<entity>

	<!-- TRAER UNA CONDICION DE PAGO Y SU DETALLE -->
	<operacion name="TraerCondPago" clase="com.jkt.varios.operaciones.TraerCondPago">

		<output name="condicion" tableName="mtCondicionDePago">
			<campoSalida value="oid_CondPago" target="id" />
			<campoSalida value="Codigo" target="codigo" />
			<campoSalida value="Descripcion" target="descripcion" />
			<campoSalida value="APartirFechaFactura" target="baseFechaFactura" />
			<campoSalida value="APartirFechaRecepcion" target="baseFechaRecep" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="detalle" tableName="mtDetalleCondicionDePago">
			<campoSalida value="oid_Det_CondPago" target="id" />
			<campoSalida value="oid_CondPago" target="condicionDePago.id" />
			<campoSalida value="Dias" target="dias" />
			<campoSalida value="Porcentaje" target="porcentaje" />
		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>

		<forms>
			<form name="FNVar0001">
			</form>
		</forms>

	</operacion>


	<!-- GUARDAR UNA CONDICION DE PAGO Y SU DETALLE -->
	<operacion name="GuardarCondPago" clase="com.jkt.operaciones.GuardarLista">

		<input name="mtCondicionDePago" keyName="objeto"
			clase="com.jkt.varios.dominio.CondPago" fieldID="oid_CondPago">
			<campoEntrada>

				<campoEntrada name="Codigo" clase="String" metodo="setCodigo" />
				<campoEntrada name="Descripcion" clase="String" metodo="setDescripcion" />
				<campoEntrada name="APartirFechaFactura" clase="Boolean"
					metodo="setBaseFechaFactura" />
				<campoEntrada name="APartirFechaRecepcion" clase="Boolean"
					metodo="setBaseFechaRecep" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />

				<campoEntrada name="mtDetalleCondicionDePago" metodo="addDetalle"
					clase="com.jkt.varios.dominio.CondPagoDet" fieldID="oid_Det_CondPago">
					<campoEntrada name="Dias" clase="Integer" metodo="setDias" />
					<campoEntrada name="Porcentaje" clase="Double" metodo="setPorcentaje" />
				</campoEntrada>

			</campoEntrada>
		</input>

		<forms>
			<form name="FNVar0001"></form>
		</forms>

	</operacion>


	<operacion name="probandoGuardarCliente"
		clase="com.jkt.erp.operaciones.EjemploParaGuardarCliente">

		<forms>
			<form name="FNVar0001"></form>
		</forms>

	</operacion>


	<!-- TRAER UN CLIENTE -->
	<operacion name="TraerCliente" clase="com.jkt.varios.operaciones.TraerCliente">
		<output name="" tableName="mtCliente">
			<campoSalida value="oid_Cliente" target="id" />
			<campoSalida value="Codigo" target="codigo" />
			<campoSalida value="RazonSocial" target="" />
			<campoSalida value="Direccion" target="" />
			<campoSalida value="Localidad" target="" />
			<campoSalida value="CodPostal" target="" />
			<campoSalida value="oid_Provincia" target="" />
			<campoSalida value="CodProvincia" target="" />
			<campoSalida value="DescProvincia" target="" />
			<campoSalida value="oid_Pais" target="" />
			<campoSalida value="CodPais" target="" />
			<campoSalida value="DescPais" target="" />
			<campoSalida value="Telefonos" target="" />
			<campoSalida value="PersonaJuridica" target="" />
			<campoSalida value="Cuit" target="" />
			<campoSalida value="oid_CondPago" target="" />
			<campoSalida value="CodCondPago" target="" />
			<campoSalida value="DescCondPago" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="" tableName="mtInscripImposit">
			<campoSalida value="oid_InscClie" target="id" />
			<campoSalida value="oid_Cliente" target="" />
			<campoSalida value="oid_Impuesto" target="" />
			<campoSalida value="DescImpuesto" target="" />
			<campoSalida value="NroInscripcion" target="" />
			<campoSalida value="oid_Categoria" target="" />
			<campoSalida value="DescCategoria" target="" />
			<campoSalida value="VigenciaDesde" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="" tableName="mtClasificadoresCliente">
			<campoSalida value="oid_ClasifClie" target="id" />
			<campoSalida value="oid_Cliente" target="" />
			<campoSalida value="DescClasif" target="" />
			<campoSalida value="oid_ValorClasif" target="" />
			<campoSalida value="CodValorClasif" target="" />
			<campoSalida value="DescValorClasif" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="" tableName="mtSucursalesCliente">
			<campoSalida value="oid_SucClie" target="id" />
			<campoSalida value="oid_Cliente" target="" />
			<campoSalida value="NroSucursal" target="" />
			<campoSalida value="Descripcion" target="" />
			<campoSalida value="Direccion" target="" />
			<campoSalida value="Localidad" target="" />
			<campoSalida value="CodPostal" target="" />
			<campoSalida value="oid_Provincia" target="" />
			<campoSalida value="CodProvincia" target="" />
			<campoSalida value="DescProvincia" target="" />
			<campoSalida value="oid_Vendedor" target="" />
			<campoSalida value="CodVendedor" target="" />
			<campoSalida value="DescVendedor" target="" />
			<campoSalida value="Telefonos" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="" tableName="mtDomiciliosEntrega">
			<campoSalida value="oid_DomSuc" target="id" />
			<campoSalida value="oid_SucClie" target="" />
			<campoSalida value="NroDomicilio" target="" />
			<campoSalida value="Descripcion" target="" />
			<campoSalida value="Direccion" target="" />
			<campoSalida value="Localidad" target="" />
			<campoSalida value="CodPostal" target="" />
			<campoSalida value="oid_Provincia" target="" />
			<campoSalida value="CodProvincia" target="" />
			<campoSalida value="DescProvincia" target="" />
			<campoSalida value="HorariosEntrega" target="" />
			<campoSalida value="Telefonos" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="" tableName="mtContactos">
			<campoSalida value="oid_ContSuc" target="id" />
			<campoSalida value="oid_SucClie" target="" />
			<campoSalida value="Apellido" target="" />
			<campoSalida value="Nombres" target="" />
			<campoSalida value="Cargo" target="" />
			<campoSalida value="Telefonos" target="" />
			<campoSalida value="Email" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<output name="" tableName="mtClasificadoresSucursal">
			<campoSalida value="oid_ClasifSuc" target="id" />
			<campoSalida value="oid_SucClie" target="" />
			<campoSalida value="DescClasif" target="" />
			<campoSalida value="oid_ValorClasif" target="" />
			<campoSalida value="CodValorClasif" target="" />
			<campoSalida value="DescValorClasif" target="" />
			<campoSalida value="Activo" target="activo" />
		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>

		<forms>
			<form name="FNCli0001">
			</form>
		</forms>

	</operacion>


	<!-- GUARDAR UN CLIENTE -->
	<operacion name="GuardarCliente" clase="com.jkt.varios.operaciones.GuardarCliente">
		<input name="mtCliente" keyName="objeto" clase="com.jkt.varios.dominio.Cliente"
			fieldID="oid_Cliente">
			<campoEntrada>
				<campoEntrada name="Codigo" clase="String" metodo="" />
				<campoEntrada name="RazonSocial" clase="String" metodo="" />
				<campoEntrada name="Direccion" clase="String" metodo="" />
				<campoEntrada name="Localidad" clase="String" metodo="" />
				<campoEntrada name="CodPostal" clase="String" metodo="" />
				<campoEntrada name="oid_Provincia" clase="String" metodo="" />
				<campoEntrada name="oid_Pais" clase="String" metodo="" />
				<campoEntrada name="Telefonos" clase="String" metodo="" />
				<campoEntrada name="PersonaJuridica" clase="Boolean" metodo="" />
				<campoEntrada name="Cuit" clase="String" metodo="" />
				<campoEntrada name="oid_CondPago" clase="String" metodo="" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				<campoEntrada name="mtInscripImposit" metodo="" clase="com.jkt.varios.dominio." fieldID="oid_InscClie">
					<campoEntrada name="oid_Impuesto" clase="" metodo="" />
					<campoEntrada name="DescImpuesto" clase="" metodo="" />
					<campoEntrada name="NroInscripcion" clase="Integer" metodo="" />
					<campoEntrada name="oid_Categoria" clase="String" metodo="" />
					<campoEntrada name="CodCategoria" clase="String" metodo="" />
					<campoEntrada name="DescCategoria" clase="String" metodo="" />
					<campoEntrada name="VigenciaDesde" clase="Date" metodo="" />
					<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				</campoEntrada>

				<campoEntrada name="mtClasificadoresCliente" metodo="" clase="com.jkt.varios.dominio." fieldID="oid_ClasifClie">
					<campoEntrada name="DescClasif" clase="String" metodo="" />
					<campoEntrada name="oid_ValorClasif" clase="String" metodo="" />
					<campoEntrada name="CodValorClasif" clase="String" metodo="" />
					<campoEntrada name="DescValorClasif" clase="String" metodo="" />
					<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				</campoEntrada>

				<campoEntrada name="mtSucursalesCliente" metodo="" clase="com.jkt.varios.dominio." fieldID="oid_SucClie">
					<campoEntrada name="NroSucursal" clase="Smallint" metodo="" />
					<campoEntrada name="Descripcion" clase="String" metodo="" />
					<campoEntrada name="Direccion" clase="String" metodo="" />
					<campoEntrada name="Localidad" clase="String" metodo="" />
					<campoEntrada name="CodPostal" clase="String" metodo="" />
					<campoEntrada name="oid_Provincia" clase="String" metodo="" />
					<campoEntrada name="oid_Vendedor" clase="String" metodo="" />
					<campoEntrada name="Telefonos" clase="String" metodo="" />
					<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />

					<campoEntrada name="mtDomiciliosEntrega" metodo="" clase="com.jkt.varios.dominio." fieldID="oid_DomSuc">
						<campoEntrada name="NroDomicilio" clase="Smallint" metodo="" />
						<campoEntrada name="Descripcion" clase="String" metodo="" />
						<campoEntrada name="Direccion" clase="String" metodo="" />
						<campoEntrada name="Localidad" clase="String" metodo="" />
						<campoEntrada name="CodPostal" clase="String" metodo="" />
						<campoEntrada name="oid_Provincia" clase="String" metodo="" />
						<campoEntrada name="HorariosEntrega" clase="String" metodo="" />
						<campoEntrada name="Telefonos" clase="String" metodo="" />
						<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
					</campoEntrada>

					<campoEntrada name="mtContactos" metodo=""
						clase="com.jkt.varios.dominio." fieldID="oid_ContSuc">
						<campoEntrada name="Apellido" clase="String" metodo="" />
						<campoEntrada name="Nombres" clase="String" metodo="" />
						<campoEntrada name="Cargo" clase="String" metodo="" />
						<campoEntrada name="Telefonos" clase="String" metodo="" />
						<campoEntrada name="Email" clase="String" metodo="" />
						<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
					</campoEntrada>

					<campoEntrada name="mtClasificadoresSucursal" metodo=""
						clase="com.jkt.varios.dominio." fieldID="oid_ClasifSuc">
						<campoEntrada name="DescClasif" clase="String" metodo="" />
						<campoEntrada name="oid_ValorClasif" clase="String" metodo="" />
						<campoEntrada name="CodValorClasif" clase="String" metodo="" />
						<campoEntrada name="DescValorClasif" clase="String" metodo="" />
						<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
					</campoEntrada>
				</campoEntrada>
			</campoEntrada>

		</input>

		<forms>
			<form name="FNCli0001"></form>
		</forms>

	</operacion>



	<!-- TRAER LOS CLASIFICADORES DEL CLIENTE -->
	<operacion name="TraerClasifCliente" clase="com.jkt.varios.operaciones.TraerClasifCliente">
		
		<output name="" tableName="mtClasificadoresCliente">
			<campoSalida value="oid_ClasifClie" target="id" />
			<campoSalida value="DescClasif" target="" />
		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>

		<forms>
			<form name="FNCli0001"></form>
		</forms>
	</operacion>


	<!-- TRAER LOS CLASIFICADORES DE LA SUCURSAL -->
	<operacion name="TraerClasifSucur" clase="com.jkt.varios.operaciones.TraerClasifSucur">

		<output name="" tableName="mtClasificadoresSucursal">
			<campoSalida value="oid_ClasifSuc" target="id" />
			<campoSalida value="oid_SucClie" target="" />
			<campoSalida value="DescClasif" target="" />
		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>

		<forms>
			<form name="FNCli0001">
			</form>
		</forms>

	</operacion>


</entity>
