<?xml version="1.0" ?>
<!DOCTYPE entity [
  	<!ELEMENT menu		(elementos*)>
  	<!ELEMENT elementos	(elemento*)>
	<!ELEMENT elemento	(elemento*)>
  	<!ELEMENT texto	EMPTY>
  
  	<!ATTLIST elemento codigo CDATA #REQUIRED>
	<!ATTLIST elemento name	CDATA #REQUIRED>
	<!ATTLIST elemento img	CDATA #REQUIRED>
	<!ATTLIST elemento size	CDATA #REQUIRED>
	<!ATTLIST elemento theme CDATA #REQUIRED>
	<!ATTLIST elemento link	CDATA #IMPLIED>
	<!ATTLIST elemento type	CDATA #REQUIRED>
	<!ATTLIST elemento orden	CDATA #REQUIRED>

]>

<menues>

	<elemento orden="1" codigo="501" name="Laboratorio Electrico" img="pantallas/img/labs.png" size="4x2" theme="grey" type="menu_principal">
		<elemento orden="2" codigo="004" name="Determinaciones Electricas" 		img="pantallas/img/widget_tooltip.png" 	size="4x2" theme="yellow" link="pantallas/index/index-determinacion-e.zul" 	type="submenu"  />
		<elemento orden="3" codigo="006" name="Protocolo Electrico" 			img="pantallas/img/widget_tag.png" size="4x2" theme="red" 		link="pantallas/index/index-protocolo-e.zul" 			type="submenu" />
		<elemento orden="4" codigo="007" name="Aprobar P.Electrico" 			img="pantallas/img/widget_tag.png" size="4x2" theme="darkblue" 	link="pantallas/index/index-protocolo-e-aprobacion.zul" type="submenu" />
		<elemento orden="5" codigo="022" name="Protocolo Electrico Terminado" 	img="pantallas/img/widget_tag.png" size="4x2" theme="orange" 	link="pantallas/index/index-protocolo-e-terminado.zul" 	type="submenu"  />
		<elemento orden="6" codigo="023" name="Protocolo Electrico A Enviar" 	img="pantallas/img/widget_tag.png" size="4x2" theme="green" 	link="pantallas/index/index-protocolo-e-a-enviar.zul" 	type="submenu"  />
	</elemento>

	<elemento codigo="401" orden="6" name="Laboratorio Quimico" img="pantallas/img/labs.png" size="4x2" theme="grey" type="menu_principal">
		<elemento codigo="005" orden="7" 	name="Determinaciones Quimicas" 	img="pantallas/img/widget_tooltip.png" 	size="4x2" theme="green" 	link="pantallas/index/index-determinacion-q.zul" 		type="submenu" />
		<elemento codigo="008" orden="8" 	name="Protocolo Quimico" 			img="pantallas/img/widget_tag.png" 		size="4x2" theme="red" 		link="pantallas/index/index-protocolo-q.zul" 			type="submenu" />
		<elemento codigo="009" orden="9" 	name="Aprobar P.Quimico" 			img="pantallas/img/widget_tag.png" 		size="4x2" theme="green" 	link="pantallas/index/index-protocolo-q-aprobacion.zul" type="submenu"  />
		<elemento codigo="023" orden="10" 	name="Protocolo Quimico Terminado" 	img="pantallas/img/widget_tag.png" 		size="4x2" theme="orange" 	link="pantallas/index/index-protocolo-q-terminado.zul" 	type="submenu"  />
		<elemento codigo="024" orden="11" 	name="Protocolo Quimico A Enviar" 	img="pantallas/img/widget_tag.png" 		size="4x2" theme="blue" 	link="pantallas/index/index-protocolo-q-a-enviar.zul" 	type="submenu"  />
	</elemento>

	<elemento codigo="001" orden="11" name="Equipos" img="pantallas/img/labs.png" size="4x2" theme="grey" type="menu_principal">
		<elemento codigo="003" orden="12" name="Equipo" 						img="pantallas/img/widget_tag.png" 	size="2x2" theme="grey" link="pantallas/index/index-equipo.zul" type="submenu"  />
		<elemento codigo="9999" orden="13" name="Historia de Equipos" 		img="pantallas/img/widget_tag.png" 	size="4x2" theme="grey" link="pantallas/index/index-estadistica-equipo.zul" type="submenu" />
	</elemento>

	<elemento codigo="010" orden="13" name="Ventas" img="pantallas/img/widget_map.png" size="4x2" theme="red" type="menu_principal">
		<elemento codigo="011" orden="14" name="Cotizacion" 				img="pantallas/img/widget_dialog.png" 	size="4x2" theme="darkblue" link="pantallas/index/index-cotizacion.zul" 		type="submenu" />  
		<elemento codigo="012" orden="15" name="Modelo de Cotizador" 		img="pantallas/img/modeloCotizador.png" size="2x2" theme="orange" 	link="pantallas/index/index-modeloCotizador.zul" 	type="submenu" />  
		<elemento codigo="013" orden="16" name="Conceptos Presupuestarios" img="pantallas/img/modeloCotizador.png" 	size="2x2" theme="orange" 	link="pantallas/index/index-conceptos.zul" 			type="submenu" />
		<elemento codigo="014" orden="17" name="Cotizador" 					img="pantallas/img/cotizador.png" 		size="4x2" theme="grey" 	link="pantallas/index/index-cotizador.zul" 			type="submenu" 	/>  
		<elemento codigo="015" orden="18" name="Presupuesto" 				img="pantallas/img/presupuesto.png" 	size="4x2" theme="orange" 	link="pantallas/index/index-presupuesto.zul" 		type="submenu" />  
		<elemento codigo="016" orden="19" name="Pedido" 					img="pantallas/img/order.png" 			size="4x2" theme="green" 	link="pantallas/index/index-pedido.zul" 			type="submenu" />  
		<elemento codigo="017" orden="20" name="Planificacion de Pedido" 	img="pantallas/img/calendar_tasks.png" 	size="4x2" theme="white" 	link="pantallas/index/index-agenda.zul" 			type="submenu" />  
		

		<elemento codigo="018" orden="21" name="Visores de Tareas" 		img="pantallas/img/planificacion.png" 	size="2x2" theme="red" type="menu" >
			<elemento codigo="019" orden="22" name="Tareas por Sector" 	img="pantallas/img/planificacion.png" 	size="4x2" theme="blue" 	link="pantallas/index/index-vista-agenda-sector.zul" 	type="submenu"  />
			<elemento codigo="020" orden="23" name="Tareas por Pedido" 	img="pantallas/img/planificacion.png" 	size="4x2" theme="orange" 	link="pantallas/index/index-vista-agenda-pedido.zul" 	type="submenu"  />
			<elemento codigo="021" orden="24" name="Visor Interactivo" 	img="pantallas/img/widget_char.png" 	size="4x2" theme="darkblue" link="pantallas/index/visor-agenda.zul" 				type="submenu"  />
		</elemento>
		
		<elemento codigo="019" orden="22" name="Configuracion de estados" 	img="pantallas/img/modeloCotizador.png" 	size="2x2" theme="blue" type="menu" >
			<elemento codigo="020" orden="24" name="Estados" 			img="pantallas/img/planificacion.png" 	size="2x2" theme="orange" 	link="pantallas/generic/genericList.zul?metadata=guardarEstadoTareas-estado" type="submenu" />
			<elemento codigo="021" orden="25" name="Maquina de estados" img="pantallas/img/planificacion.png" 	size="2x2" theme="green" 	link="pantallas/index/index-maquinaEstados.zul"								 type="submenu" />
		</elemento>

		<elemento codigo="036" orden="36" name="Actividad" 			img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarActividad-actividad" 		type="submenu"  />
		<elemento codigo="037" orden="37" name="Notas" 				img="pantallas/img/widget_dialog.png" 	size="2x2" theme="orange" 	link="pantallas/index/index-nota.zul" 												type="submenu"/>  
		<elemento codigo="038" orden="38" name="Representantes" 	img="pantallas/img/widget_dialog.png" 	size="2x2" theme="green" 	link="pantallas/index/index-representante.zul" 										type="submenu"  />
		<elemento codigo="039" orden="39" name="Tipo de Contacto"	img="pantallas/img/widget_dialog.png" 	size="2x2" theme="blue" 	link="pantallas/generic/genericList.zul?metadata=guardarTipoContacto-tipoContacto" 	type="submenu"  />
		<elemento codigo="040" orden="40" name="Vendedores" 		img="pantallas/img/widget_dialog.png" 	size="2x2" theme="red" 		link="pantallas/index/index-vendedor.zul" 											type="submenu"  />
		<elemento codigo="041" orden="41" name="CondiciÃ³n de Pago" 	img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/index/index-condicionPago.zul" 										type="submenu"  />
		<elemento codigo="042" orden="42" name="Clientes" 			img="pantallas/img/widget_dialog.png" 	size="4x2" theme="orange" 	link="pantallas/index/index-cliente.zul" 											type="submenu"  />
		<elemento codigo="043" orden="43" name="Impuestos" 			img="pantallas/img/widget_dialog.png" 	size="2x2" theme="white" 	link="pantallas/index/index-impuesto.zul" 											type="submenu"  />
	</elemento>
	
	<elemento codigo="100" orden="25" name="Utilidades" img="pantallas/img/widget_dialog.png" size="4x2" theme="blue" type="menu_principal">
		<elemento codigo="002" orden="26" name="Laboratorio" 					img="pantallas/img/labs.png" 			size="2x2" theme="grey" link="pantallas/index/index-laboratorio.zul" 							type="submenu" />
		<elemento codigo="108" orden="27" name="Plantilla" 	img="pantallas/img/widget_dialog.png" 	size="2x2" theme="red" 		link="pantallas/index/plantilla.zul"									 				type="submenu" />
		<elemento codigo="101" orden="28" name="Sector" 		img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarSector-sector" 				type="submenu" />
		<elemento codigo="102" orden="29" name="Tarea" 		img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarTareaSimple-tarea" 			type="submenu" />

		<elemento codigo="103" orden="30" name="Unidad Medida" img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarUnidadMedida-unidadMedida" 	type="submenu"  />
		<elemento codigo="104" orden="31" name="Idioma" 		img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarIdioma-idioma" 				type="submenu"  />
		<elemento codigo="105" orden="32" name="Moneda" 		img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarMoneda-moneda" 				type="submenu"  />
		<elemento codigo="106" orden="33" name="Pais" 			img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarPais-pais" 					type="submenu"  />
		<elemento codigo="107" orden="34" name="Documentacion" 	img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarDocumentacion-documentacion" type="submenu" />
		<elemento codigo="110" orden="35" name="Diagnostico" 	img="pantallas/img/widget_dialog.png" 	size="2x2" theme="darkblue" link="pantallas/generic/genericList.zul?metadata=guardarDiagnostico-diagnostico" 	type="submenu"  />
	</elemento>
	
</menues>

