<?xml version="1.0" ?>
<!DOCTYPE entity [
  <!ELEMENT entidad     	(operacion, campos*,validadores*)>
  <!ELEMENT campos   		(campo*)>
  <!ELEMENT campo 			EMPTY>
  
  <!ELEMENT validadores 	(validador*)>
  <!ELEMENT validador 		EMPTY>
  
  <!ATTLIST entidad nombre	CDATA #REQUIRED>
  
  <!ATTLIST operacion operSave CDATA #REQUIRED>
  <!ATTLIST operacion operTraer CDATA #REQUIRED>

  <!ATTLIST campo fieldName CDATA #REQUIRED>
  <!ATTLIST campo tipo CDATA #REQUIRED>
  <!ATTLIST campo longitud CDATA #REQUIRED>
  <!ATTLIST campo readOnly CDATA #REQUIRED>
  <!ATTLIST campo visible CDATA #REQUIRED>
  <!ATTLIST campo orden CDATA #REQUIRED>
  <!ATTLIST campo label CDATA #REQUIRED>
  <!ATTLIST campo tag   CDATA "1"  >

  <!ATTLIST validador fieldName CDATA #REQUIRED>
  <!ATTLIST validador tipoValidacion CDATA #REQUIRED>
  <!ATTLIST validador entidad CDATA #REQUIRED>
  <!ATTLIST validador oidName CDATA #REQUIRED>
  <!ATTLIST validador descrName CDATA #REQUIRED>
  
]>

<entidades>
		
	
<entidad nombre="TablaValidacionCaracProducto">

		<operacion operSave="GuardarTablaValCarac" operTraer="TraerTablaValCarac" />
		
		<campos>
			<campo fieldName="oid_tabla" tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid_tabla"  />
			<campo fieldName="Codigo" tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="descr"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Descripcion"  />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="4" label="Activo"   />
		</campos>

		<validadores>
			<validador fieldName="Codigo" tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="descr" tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
		</validadores>
		
	</entidad>
	
<entidad nombre="CaracProducto">

		<operacion operSave="GuardarCaracProducto" operTraer="TraerCaracProducto" />
		
		<campos>
			<campo fieldName="oid_carac" tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid_carac" />
			<campo fieldName="Codigo" tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="descr"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Descripcion"  />
			<campo fieldName="tipo_dato"  tipo="String" longitud="20" visible="true" readOnly="false" orden="4" label="Tipo de Dato"  />
			<campo fieldName="cod_tabla"  tipo="String" longitud="10" visible="true" readOnly="false" orden="5" label="Tabla" tag="0"/>
			<campo fieldName="des_tabla"  tipo="String" longitud="60" visible="true" readOnly="true" orden="6" label="Descripcion" tag="0" />
			<campo fieldName="oid_tabla"  tipo="Integer" longitud="0" visible="false" readOnly="false" orden="7" label="oid"  />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="8" label="Activo" />
		</campos>

		<validadores>
			<validador fieldName="Codigo"     tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="descr"      tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="cod_tabla"  tipoValidacion="Existente" entidad="TablaValoresCaracProd" oidName="oid_tabla" descrName="des_tabla" />
		</validadores>
		
	</entidad>

<entidad nombre="Idioma">

		<operacion operSave="GuardarIdioma" operTraer="TraerIdioma" />
		
		<campos>
			<campo fieldName="oid"    tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid" />
			<campo fieldName="Codigo" tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="descr"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Descripcion"  />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="4" label="Activo" />
		</campos>

		<validadores>
			<validador fieldName="Codigo"     tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="descr"      tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
		</validadores>
		
	</entidad>



<entidad nombre="Pais">

		<operacion operSave="GuardarPais" operTraer="TraerPais" />
		
		<campos>
			<campo fieldName="oid"    tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid_carac" />
			<campo fieldName="Codigo" tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="descr"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Descripcion"  />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="4" label="Activo" />
		</campos>

		<validadores>
			<validador fieldName="Codigo"     tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="descr"      tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
		</validadores>
		
	</entidad>

<entidad nombre="Provincia">
<operacion operSave="GuardarProvincia" operTraer="TraerProvincia" />
		
		<campos>
			<campo fieldName="oid_prov" tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid_carac" />
			<campo fieldName="Codigo" tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="descr"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Descripcion"  />
			<campo fieldName="cod_pais"  tipo="String" longitud="10" visible="true" readOnly="false" orden="5" label="Pais" tag="0"/>
			<campo fieldName="des_pais"  tipo="String" longitud="60" visible="true" readOnly="true" orden="6" label="Descripcion" tag="0" />
			<campo fieldName="oid_pais"  tipo="Integer" longitud="0" visible="false" readOnly="false" orden="7" label="oid"  />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="8" label="Activo" />
		</campos>

		<validadores>
			<validador fieldName="Codigo"     tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="descr"      tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="cod_pais"   tipoValidacion="Existente" entidad="Pais" oidName="oid_pais" descrName="des_pais" />
		</validadores>
		
	</entidad>


<entidad nombre="Vendedor">

		<operacion operSave="GuardarVendedor" operTraer="TraerVendedor" />
		
		<campos>
			<campo fieldName="oid"       tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid_carac" />
			<campo fieldName="codigo"    tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="apellido"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Apellido"  />
			<campo fieldName="nombres"   tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Nombres"  />
			<campo fieldName="mail"      tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Mail"  />
			<campo fieldName="telefono"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Telefono"  />
			<campo fieldName="Activo"    tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="4" label="Activo" />
		</campos>

		<validadores>
			<validador fieldName="codigo"       tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="apellido"     tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="nombres"      tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
		</validadores>
		
	</entidad>


<entidad nombre="Representante">

		<operacion operSave="GuardarRepresentante" operTraer="TraerRepresentante" />
		
		<campos>
			<campo fieldName="oid"    tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid_carac" />
			<campo fieldName="Codigo" tipo="String" longitud="15" visible="true" readOnly="false" orden="2" label="Codigo"  />
			<campo fieldName="descr"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Descripcion"  />
			<campo fieldName="mail"      tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Mail"  />
			<campo fieldName="telefono"  tipo="String" longitud="60" visible="true" readOnly="false" orden="3" label="Telefono"  />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="4" label="Activo" />
		</campos>

		<validadores>
			<validador fieldName="Codigo"     tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
			<validador fieldName="descr"      tipoValidacion="DistintoEspacio" entidad="" oidName="" descrName="" />
		</validadores>
		
	</entidad>


	
</entidades>