<?xml version="1.0" ?>
<!DOCTYPE entity [
  <!ELEMENT entidad     	(campos*)>
  <!ELEMENT campos   		(campo*)>
  <!ELEMENT campo 			EMPTY>
  
  <!ATTLIST entidad nombre	CDATA #REQUIRED>

  <!ATTLIST campo fieldName CDATA #REQUIRED>
  <!ATTLIST campo tipo CDATA #REQUIRED>
  <!ATTLIST campo longitud CDATA #REQUIRED>
  <!ATTLIST campo readOnly CDATA #REQUIRED>
  <!ATTLIST campo visible CDATA #REQUIRED>
  <!ATTLIST campo orden CDATA #REQUIRED>
  <!ATTLIST campo label CDATA #REQUIRED>

]>

<entidades>
	<entidad nombre="empresa">

		<campos>
			<campo fieldName="oid_empresa" tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid" />
			<campo fieldName="Codigo" tipo="String" longitud="50" visible="true" readOnly="false" orden="2" label="codigo" />
			<campo fieldName="RazonSocial" tipo="String" longitud="200" visible="true" readOnly="false" orden="3" label="Razon Social" />
			<campo fieldName="UrlDB" tipo="String" longitud="60" visible="true" readOnly="false" orden="4" label="UrlDB" />
			<campo fieldName="Activo" tipo="Boolean" longitud="5" visible="true" readOnly="false" orden="5" label="Activo" />
			
		</campos>

	</entidad>

	<entidad nombre="entidad">

		<campos>
			<campo fieldName="oid" tipo="Integer" longitud="0" visible="false" readOnly="false" orden="1" label="oid" />
			<campo fieldName="Codigo" tipo="String" longitud="50" visible="true" readOnly="false" orden="2" label="codigo" />
			<campo fieldName="Descripcion" tipo="String" longitud="200" visible="true" readOnly="false" orden="3" label="Descripcion" />
		</campos>

	</entidad>
	
</entidades>