<?xml version="1.0" standalone="yes"?>
<!DOCTYPE entity [

  <!ELEMENT entity        (operacion*)>
  <!ELEMENT operacion     (input* , output*,transformer)>
<!--   <!ELEMENT operacion     (input* , output* , dataset* , tables*, transformer?, forms)> -->
  
  <!ELEMENT input		  (campoEntrada*)>	<!--   Es la entrada de la operacion. Lo definido aquí llegará en un mapa a la operacion -->
  <!ELEMENT output		  (campoSalida*)> 	<!--   Define el formato de salida -->
  <!ELEMENT transformer	  EMPTY>			<!--   Define una clase que es la encargada de mostrar los resultados en la salida de la operacion. (Muchas tablas, una sola, en paralelo) -->
  
  <!ELEMENT listas		  (lista*)>			<!--   Son las listas para mostrar en la salida-->

  <!ELEMENT lista  (lista*)>  
  <!ATTLIST lista nombreWriter		CDATA    #REQUIRED>
  <!ATTLIST lista nombreLista       CDATA    #REQUIRED>


  <!ELEMENT campoEntrada  (input*|campoEntrada*)>  
  <!ELEMENT campoSalida   (campoSalida*,output*)>  
  
  <!ATTLIST transformer clase           CDATA #REQUIRED>
  
  <!ATTLIST input nameOV           	 	CDATA    "OV"><!--   Nombre que se corresponde con el name del objectview. -->
  <!ATTLIST input keyName           	CDATA    #IMPLIED><!--   Indica el key del mapa que llega a la operacion. Si el valor es 'leo', se debera recuperar usando la key 'leo' sobre el mapa en la operacion -->
  <!ATTLIST input clase           	 	CDATA    #IMPLIED><!-- 	define la clase del parmetro recibido -->
  <!ATTLIST input fieldID           	CDATA    "id"><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base -->
  <!ATTLIST input nombreEntidad        	CDATA    #IMPLIED>
  
  <!ATTLIST campoEntrada metodo			CDATA #IMPLIED>
  <!ATTLIST campoEntrada name			CDATA #IMPLIED>
  <!ATTLIST campoEntrada propertyOV		CDATA #REQUIRED>
  <!ATTLIST campoEntrada fieldID        CDATA    "id"><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base -->
 
 
  <!ATTLIST output name					CDATA "outputName"> <!-- Para web, nombre del objeto notificado a setear--> 
  <!ATTLIST output clase				CDATA #IMPLIED> <!-- Clase del tipo OV (vista) a la que se debe convertir el objeto-->
  
  <!ATTLIST campoSalida target			CDATA #IMPLIED> <!-- El nombre del metodo para recuperar los datos -->
  <!ATTLIST campoSalida value			CDATA #IMPLIED> <!-- el valor de la property que contendra el valor de resltado de target -->

  <!ATTLIST operacion name              ID    #REQUIRED>
  <!ATTLIST operacion clase             CDATA #IMPLIED>
  <!ATTLIST operacion entidad           CDATA #IMPLIED>
  <!ATTLIST operacion inputOV            CDATA #IMPLIED>
  <!ATTLIST operacion outputOV            CDATA #IMPLIED>
]>

<entity>

	<operacion name="saveLabo" clase="com.jkt.operaciones.Guardar" entidad="com.jkt.laboratorio.dominio.Laboratorio" inputOV="com.jkt.ov.LaboratorioOV">
		
		<input keyName="objeto" clase="com.jkt.laboratorio.dominio.Laboratorio">
			<campoEntrada propertyOV="id" metodo="setId" />
			<campoEntrada propertyOV="codigo" metodo="setCodigo" />
			<campoEntrada propertyOV="descripcion" metodo="setDescripcion" />
			<campoEntrada propertyOV="activo" metodo="setActivo" />
		</input>

		<transformer clase="com.jkt.transformers.WebTransformer" />
	</operacion>

	<operacion name="TraerLabo" clase="com.jkt.operaciones.TraerEntidadesRelacionWeb" entidad="com.jkt.laboratorio.dominio.Laboratorio" outputOV="com.jkt.ov.ListLaboratorioOV">
		
		<output>

			<campoSalida target="id" value="id" />
			<campoSalida target="codigo" value="codigo" />
			<campoSalida target="descripcion" value="descripcion" />
			<campoSalida target="activo" value="isActivo" />
			
		</output>

		<transformer clase="com.jkt.transformers.WebTransformer" />
	</operacion>

</entity>
	