<?xml version="1.0" standalone="yes"?>
<!DOCTYPE entity [

<!--   <!ENTITY operacionesExternas SYSTEM "file:///operaciones-2.xml"> -->
	
  <!ELEMENT entity        (operacion*)>
  <!ELEMENT operacion     (input* , output* , dataset* , tables*, transformer?, forms)>
  
  <!ELEMENT input		  (campoEntrada*)>	<!--   Es la entrada de la operacion. Lo definido aquí llegará en un mapa a la operacion -->
  <!ELEMENT forms		  (form*)>		  	<!--   Para definir una restriccion y conocer que clients utilizan esta operacion. Es a modo de mantenimiento, por ejemplo: al cambiar una operacion, se debe saber quienes suelen llamar a la operacion para realizar los debidos cambios -->
  <!ELEMENT output		  (campoSalida*)> 	<!--   Define el formato de salida -->
  <!ELEMENT transformer	  EMPTY>			<!--   Define una clase que es la encargada de mostrar los resultados en la salida de la operacion. (Muchas tablas, una sola, en paralelo) -->


  <!ELEMENT campoEntrada  (input*|campoEntrada*)>  
  <!ELEMENT campoSalida   (campoSalida*,output*)>  
  
  <!ELEMENT dataset       (campo*)>
  <!ELEMENT campo         EMPTY>
  <!ELEMENT tables       (tableDef+)>
  <!ELEMENT tableDef     (campoTable*)>
  <!ELEMENT campoTable   EMPTY>
  
  <!ATTLIST transformer clase           CDATA #REQUIRED>
  
  <!ATTLIST form name	CDATA #REQUIRED>
  
  <!ATTLIST input name           	 	CDATA    #IMPLIED><!--   Nombre que se corresponde con la entrada de delphi. Si en delphi mandan el valor Name, acá debe exstir en valor Name para obtener los demas datos -->
  <!ATTLIST input keyName           	CDATA    #IMPLIED><!--   Indica el key del mapa que llega a la operacion. Si el valor es 'leo', se debera recuperar usando la key 'leo' sobre el mapa en la operacion -->
  <!ATTLIST input clase           	 	CDATA    #IMPLIED><!-- 	define la clase del parmetro recibido -->
  <!ATTLIST input fieldID           	CDATA    #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
  <!ATTLIST input nombreEntidad        	CDATA    #IMPLIED>
  
  <!ATTLIST campoEntrada name			CDATA #IMPLIED>
  <!ATTLIST campoEntrada clase			CDATA #IMPLIED>
  <!ATTLIST campoEntrada nombreEntidad	CDATA #IMPLIED>
  <!ATTLIST campoEntrada metodo			CDATA #IMPLIED>
  <!ATTLIST campoEntrada fieldID        CDATA    #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
 
  <!ATTLIST output name					CDATA #REQUIRED> 
  <!ATTLIST output tableName           	CDATA #REQUIRED><!-- va a representar el nombre de la tabla -->

  <!ATTLIST campoSalida tableName		CDATA #IMPLIED> <!-- en caso de ser hijo de otro campoSalida, es una tabla, y este campo tendra el nombre de la tabla -->
  <!ATTLIST campoSalida target			CDATA #IMPLIED> <!-- El nombre del metodo para recuperar los datos -->
  <!ATTLIST campoSalida value			CDATA #IMPLIED> <!-- el valor de la columna que contendra el valor de resltado de target -->

  <!ATTLIST operacion name              ID    #REQUIRED>
  <!ATTLIST operacion clase             CDATA #IMPLIED>
  <!ATTLIST operacion entidad           CDATA #IMPLIED>
  <!ATTLIST operacion XMLWriter         CDATA #IMPLIED>
  <!ATTLIST operacion redirect          CDATA #IMPLIED>
  <!ATTLIST operacion usaJMS            CDATA #IMPLIED>
  
  <!ATTLIST dataset name                CDATA #REQUIRED>
  <!ATTLIST dataset value               CDATA #IMPLIED>
  <!ATTLIST dataset tabla               CDATA #IMPLIED>
  
  <!ATTLIST campo   name                CDATA #REQUIRED>
  <!ATTLIST campo   value               CDATA #IMPLIED>
  
  <!ATTLIST tableDef    name           	CDATA #REQUIRED>

  <!ATTLIST campoTable	name        	CDATA #REQUIRED>
  <!ATTLIST campoTable  orden       	CDATA #IMPLIED>
  <!ATTLIST campoTable  tipo        	CDATA #IMPLIED>
  <!ATTLIST campoTable  longitud    	CDATA #IMPLIED>
  
]>

<entity>
	

	<operacion name="FiltroActivos" clase="com.jkt.operaciones.HelperActivos">
		<!-- 		ESTO NO VA, VER LA FORMA DE ELIMINAR Y PERMITIR TABLAS SIN DATOS, TABLAS VACIAS -->
		<input name="mtFiltros" keyName="filtros" clase="com.jkt.dominio.Filtro" fieldID="-">
		</input>
		
		<output name="resultado" tableName="mtInput">
			<campoSalida value="oid" target="id" />
			<campoSalida value="Codigo" target="codigo" />
			<campoSalida value="Descripcion" target="cadena" />
		</output>		
		
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TUsuario"></form>
		</forms>
	</operacion>



	<operacion name="FiltroInactivos" clase="com.jkt.operaciones.HelperInactivos">

<!-- 		ESTO NO VA, VER LA FORMA DE ELIMINAR Y PERMITIR TABLAS SIN DATOS, TABLAS VACIAS -->
		<input name="mtFiltros" keyName="filtros" clase="com.jkt.dominio.Filtro" fieldID="-">
<!-- 		el guion en el field id es para que no busque  -->
		</input>

		<output name="resultado" tableName="mtInput">
			<campoSalida value="oid" target="id" />
			<campoSalida value="Codigo" target="codigo" />
			<campoSalida value="Descripcion" target="cadena" />
		</output>		
		
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TUsuario"></form>
		</forms>
	</operacion>


	<operacion name="FiltroAvanzado" clase="com.jkt.operaciones.Helper">
		<input name="mtFiltros" keyName="filtros" clase="com.jkt.dominio.Filtro">
			<campoEntrada>
				<campoEntrada name="nombre" clase="String" metodo="setNombre" />
				<campoEntrada name="valor" clase="String" metodo="setValor" />
				<campoEntrada name="condicion" clase="String" metodo="setCondicion" />
				<campoEntrada name="tipoDeDato" clase="String" metodo="setTipoDeDato" />
			</campoEntrada>
		</input>

		<output name="resultado" tableName="mtInput">
			<campoSalida value="oid" target="id" />
			<campoSalida value="Codigo" target="codigo" />
			<campoSalida value="Descripcion" target="cadena" />
		</output>		
		
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TUsuario"></form>
		</forms>
	</operacion>
	
</entity>
