<?xml version="1.0" standalone="yes"?>
<!DOCTYPE entity [

<!--   <!ENTITY operacionesExternas SYSTEM "file:///operaciones-2.xml"> -->
	
  <!ELEMENT entity        (operacion*)>
  <!ELEMENT operacion     (input* , output* , dataset* , tables*, transformer?, forms)>
  
  <!ELEMENT input		  (campoEntrada*)>	<!--   Es la entrada de la operacion. Lo definido aquí llegará en un mapa a la operacion -->
  <!ELEMENT forms		  (form*)>		  	<!--   Para definir una restriccion y conocer que clients utilizan esta operacion. Es a modo de mantenimiento, por ejemplo: al cambiar una operacion, se debe saber quienes suelen llamar a la operacion para realizar los debidos cambios -->
  <!ELEMENT output		  (campoSalida*)> 	<!--   Define el formato de salida -->
  <!ELEMENT transformer	  EMPTY>			<!--   Define una clase que es la encargada de mostrar los resultados en la salida de la operacion. (Muchas tablas, una sola, en paralelo) -->


  <!ELEMENT campoEntrada  (input*|campoEntrada*)>  
  <!ELEMENT campoSalida   (campoSalida*,output*)>  
  
  <!ELEMENT dataset       (campo*)>
  <!ELEMENT campo         EMPTY>
  <!ELEMENT tables       (tableDef+)>
  <!ELEMENT tableDef     (campoTable*)>
  <!ELEMENT campoTable   EMPTY>
  
  <!ATTLIST transformer clase           CDATA #REQUIRED>
  
  <!ATTLIST form name	CDATA #REQUIRED>
  
  <!ATTLIST input name           	 	CDATA    #IMPLIED><!--   Nombre que se corresponde con la entrada de delphi. Si en delphi mandan el valor Name, acá debe exstir en valor Name para obtener los demas datos -->
  <!ATTLIST input keyName           	CDATA    #IMPLIED><!--   Indica el key del mapa que llega a la operacion. Si el valor es 'leo', se debera recuperar usando la key 'leo' sobre el mapa en la operacion -->
  <!ATTLIST input clase           	 	CDATA    #IMPLIED><!-- 	define la clase del parmetro recibido -->
  <!ATTLIST input fieldID           	CDATA    #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
  <!ATTLIST input nombreEntidad        	CDATA    #IMPLIED>
  
  <!ATTLIST campoEntrada name			CDATA #IMPLIED>
  <!ATTLIST campoEntrada clase			CDATA #IMPLIED>
  <!ATTLIST campoEntrada nombreEntidad	CDATA #IMPLIED>
  <!ATTLIST campoEntrada metodo			CDATA #IMPLIED>
  <!ATTLIST campoEntrada fieldID        CDATA #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
 
  <!ATTLIST output name					CDATA #REQUIRED> 
  <!ATTLIST output tableName           	CDATA #REQUIRED><!-- va a representar el nombre de la tabla -->

  <!ATTLIST campoSalida tableName		CDATA #IMPLIED> <!-- en caso de ser hijo de otro campoSalida, es una tabla, y este campo tendra el nombre de la tabla -->
  <!ATTLIST campoSalida target			CDATA #IMPLIED> <!-- El nombre del metodo para recuperar los datos -->
  <!ATTLIST campoSalida value			CDATA #IMPLIED> <!-- el valor de la columna que contendra el valor de resltado de target -->

  <!ATTLIST operacion name              ID    #REQUIRED>
  <!ATTLIST operacion clase             CDATA #IMPLIED>
  <!ATTLIST operacion entidad           CDATA #IMPLIED>
  <!ATTLIST operacion XMLWriter         CDATA #IMPLIED>
  <!ATTLIST operacion redirect          CDATA #IMPLIED>
  <!ATTLIST operacion usaJMS            CDATA #IMPLIED>
  
  <!ATTLIST dataset name                CDATA #REQUIRED>
  <!ATTLIST dataset value               CDATA #IMPLIED>
  <!ATTLIST dataset tabla               CDATA #IMPLIED>
  
  <!ATTLIST campo   name                CDATA #REQUIRED>
  <!ATTLIST campo   value               CDATA #IMPLIED>
  
  <!ATTLIST tableDef    name           	CDATA #REQUIRED>

  <!ATTLIST campoTable	name        	CDATA #REQUIRED>
  <!ATTLIST campoTable  orden       	CDATA #IMPLIED>
  <!ATTLIST campoTable  tipo        	CDATA #IMPLIED>
  <!ATTLIST campoTable  longitud    	CDATA #IMPLIED>
  
]>

<entity>

	<!-- GUARDAR Tipo de Producto	 -->
	<operacion name="GuardarTipoProducto" clase="com.jkt.operaciones.Guardar">
		<input name="mtTipoProd" keyName="objeto" clase="com.jkt.erp.articulos.TipoProducto" fieldID="oid_tipo">
			<campoEntrada >		
				<campoEntrada name="Codigo" clase="String"  metodo="setCodigo" />
				<campoEntrada name="Descr"  clase="String" 	metodo="setDescripcion" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				
				<campoEntrada name="mtDet" metodo="addCaracteristica" clase="com.jkt.erp.articulos.TipoProductoDet" fieldID="oid_tipo_det"  >
					<campoEntrada name="oid_carac" 	clase="com.jkt.erp.articulos.CaracteristicaProducto" metodo="setCaracteristica" />
					<campoEntrada name="oblig" 		clase="Boolean" metodo="setObligatorio" />
					<campoEntrada name="arma_cod" 	clase="Boolean" metodo="setArmaCodigo" />
					<campoEntrada name="arma_desc" 	clase="Boolean" metodo="setArmaDescripcion" />
					<campoEntrada name="orden" 		clase="Integer" metodo="setOrden" />
				</campoEntrada>
			</campoEntrada>
		</input>
		
		<forms>
			<form name="FNVar0001"></form>
		</forms>
		
	</operacion>

	<!-- RECUPERAR Tipo Producto -->
	<operacion name="TraerTipoProducto" clase="com.jkt.erp.articulos.operaciones.TraerTipoProducto" >
<!-- 		<input name="mtTipoProd" keyName="objeto" clase="com.jkt.erp.articulos.TipoProducto" fieldID="oid_tipo"> -->
<!-- 		</input>			 -->
		<output name="out1" tableName="mtTipoProd">
			<campoSalida value="oid_tipo" 	target="id" />
			<campoSalida value="Codigo" 	target="codigo" />
			<campoSalida value="descr" 		target="descripcion" />
			<campoSalida value="Activo" 	target="isActivo" />
		</output>
		
		<output name="out2" tableName="mtDet">
			<campoSalida value="oid_det" 	target="id" />
			<campoSalida value="oid_tipo" 	target="tipoProducto.id" />
			<campoSalida value="orden" 	    target="orden" />
			<campoSalida value="oid_carac" 	target="caracteristica.id" />
			<campoSalida value="cod_carac" 	target="caracteristica.codigo" />
			<campoSalida value="des_carac" 	target="caracteristica.descripcion" />
			<campoSalida value="Activo" 	target="isActivo" />
			<campoSalida value="oblig" 		target="isObligatorio" />
			<campoSalida value="arma_cod" 	target="isArmaCodigo" />
			<campoSalida value="arma_desc" 	target="isArmaDescripcion" />
		</output>		
			
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TEmpresa"></form>
		</forms>
		
	</operacion>


	<!-- GUARDAR Caracteristicas de Producto  -->
	<operacion name="GuardarCaracProducto" clase="com.jkt.operaciones.GuardarLista">
		<input name="mtInput" keyName="objeto" clase="com.jkt.erp.articulos.CaracteristicaProducto" fieldID='oid_carac'>
			<campoEntrada>			
				<campoEntrada name="Codigo" clase="String" metodo="setCodigo" />
				<campoEntrada name="descr"  clase="String" metodo="setDescripcion" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				<campoEntrada name="tipo_dato" clase="String" metodo="setTipoDato" />
				<campoEntrada name="oid_tabla" clase="com.jkt.erp.articulos.TablaValoresCaracProd" metodo="setTabla" />
				
			</campoEntrada>			
		</input>		

		<forms>
			<form name=""> </form>
		</forms>
		
	</operacion>


	<!-- RECUPERAR  Caracteristicas de Producto -->
	<operacion name="TraerCaracProducto" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.erp.articulos.CaracteristicaProducto">
		<output name="resultado" tableName="mtInput">
			<campoSalida value="oid_carac" target="id" />
			<campoSalida value="Codigo"    target="codigo" />
			<campoSalida value="descr"     target="descripcion" />
			<campoSalida value="Activo"    target="isActivo" />
			<campoSalida value="tipo_dato"    target="tipoDato" />
			<campoSalida value="oid_tabla"    target="tabla.id" />
			<campoSalida value="cod_tabla"    target="tabla.codigo" />
			<campoSalida value="des_tabla"    target="tabla.descripcion" />
		</output>		
			
		<transformer clase="com.jkt.transformers.º"></transformer>
		
		<forms>
			<form name="TEmpresa"></form>
		</forms>		
	</operacion>
	
	
	<operacion name="TraerTablaValCarac" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.erp.articulos.TablaValoresCaracProd">
		<output name="resultado" tableName="mtInput">
			<campoSalida value="oid_tabla" target="id" />
			<campoSalida value="Codigo"    target="codigo" />
			<campoSalida value="descr"     target="descripcion" />
			<campoSalida value="Activo"    target="isActivo" />
		</output>		
			
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TEmpresa"></form>
		</forms>
		
	</operacion>
	
	<!-- GUARDAR Tablas Validaciones Caracteristicas de Producto  -->
	<operacion name="GuardarTablaValCarac" clase="com.jkt.operaciones.GuardarLista">
		<input name="mtInput" keyName="objeto" clase="com.jkt.erp.articulos.TablaValoresCaracProd" fieldID='oid_tabla'>
			<campoEntrada>			
				<campoEntrada name="Codigo" clase="String" metodo="setCodigo" />
				<campoEntrada name="descr"  clase="String" metodo="setDescripcion" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
			</campoEntrada>			
		</input>		
		<forms>
			<form name="TUsuario"></form>
		</forms>
	</operacion>
	
	
	
<!-- 	GUARDAR VALORES DE UNA DETERMINADA TABLA -->
	<operacion name="GuardarValoresDeTabla" clase="com.jkt.operaciones.GuardarLista">
		<input name="mtInput" keyName="objeto" clase="com.jkt.erp.articulos.TablaValoresCaracProd" fieldID='oid_tabla'>
			<campoEntrada>			

				<campoEntrada name="mtValores" metodo="addValor" clase="com.jkt.erp.articulos.ValoresTablas" fieldID="oid_valor_tabla" >
					<campoEntrada name="Codigo" clase="String" metodo="setCodigo" />
					<campoEntrada name="descr"  clase="String" metodo="setDescripcion" />
					<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				</campoEntrada>
				
			</campoEntrada>			
		</input>		
		<forms>
			<form name="TUsuario"></form>
		</forms>
	</operacion>
	
	<operacion name="TraerValoresDeTabla" clase="com.jkt.erp.articulos.operaciones.TraerValoresDeTabla" >
		<output name="valores" tableName="mtInput">
			<campoSalida value="oid_valor" target="id" />
			<campoSalida value="Codigo"    target="codigo" />
			<campoSalida value="descr"     target="descripcion" />
			<campoSalida value="Activo"    target="isActivo" />
		</output>		
			
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TEmpresa"></form>
		</forms>
		
	</operacion>

	

	<!-- 	GUARDAR un producto -->
	<operacion name="GuardarProducto" clase="com.jkt.operaciones.Guardar">
		<input name="mtProducto" keyName="objeto" clase="com.jkt.erp.articulos.Producto" fieldID="oid_producto">
			<campoEntrada >		

<!-- 				Campos simples -->
				<campoEntrada name="Codigo" clase="String"  metodo="setCodigo" />
				<campoEntrada name="Descr"  clase="String" 	metodo="setDescripcion" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				
				<campoEntrada name="descAbreviada"  clase="String" 	metodo="setDescripcionAbrev" />
				<campoEntrada name="comprable" clase="Boolean" metodo="setComprable" />
				<campoEntrada name="vendible" clase="Boolean" metodo="setVendible" />
				<campoEntrada name="stockeable" clase="Boolean" metodo="setStockeable" />
				<campoEntrada name="prodPropia" clase="Boolean" metodo="setProdPropia" />
				<campoEntrada name="bien" clase="Boolean" metodo="setBien" />
				
				<campoEntrada name="oid_unidadMedidaPrincipal" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedPrin" />
				<campoEntrada name="unidadMedidaSec" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedSec" />
				<campoEntrada name="unidadMedidaTer" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedTer" />
				
				<campoEntrada name="oid_uni_venta" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUnidadVenta" />
				<campoEntrada name="oid_uni_prod" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUnidadProduccion" />
				<campoEntrada name="oid_uni_compra" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUnidadCompra" />
				
				<campoEntrada name="oid_tipo_producto" clase="com.jkt.erp.articulos.TipoProducto" metodo="setTipoProducto" />
				
				<campoEntrada name="mtProdDet" metodo="agregarDetalle" clase="com.jkt.erp.articulos.ProductoDet" fieldID="oid_producto_det"  >
								
						<campoEntrada name="oid_caract_prod" clase="com.jkt.erp.articulos.CaracteristicaProducto" metodo="setCaracProducto" />
						
						<campoEntrada name="oid_valor_tabla" clase="com.jkt.erp.articulos.ValoresTablas" metodo="setValorTabla" />
						<campoEntrada name="string"  clase="String" 	metodo="setValorString" />
						<campoEntrada name="entero"  clase="Integer" 	metodo="setValorEntero" />
						<campoEntrada name="doble"  clase="Double" 	metodo="setValorDoble" />
						<campoEntrada name="boolean" clase="Boolean" metodo="setValorBoolean" />
						<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
						
				</campoEntrada>
				
				<campoEntrada name="mtArtStock" metodo="addArticulo" clase="com.jkt.erp.articulos.ArticuloStock" fieldID="oid_art_stock"  >
<!-- 					No hace falta el producto como campo, ya que yo se que es hijo del de arriba.Es un seteo bidireccional en el metodo addArticulo -->
					<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
					<campoEntrada name="a" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedPrin" />
					<campoEntrada name="b" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedSec" />
					<campoEntrada name="c" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedTer" />
					
					
					<campoEntrada name="mtArtStockDet" metodo="agregarDetalle" clase="com.jkt.erp.articulos.ArticuloStockDet" fieldID="oid_art_stock_det"  >
								
						<campoEntrada name="a" clase="com.jkt.erp.articulos.CaracteristicaProducto" metodo="setCaracProducto" />
						<campoEntrada name="b" clase="com.jkt.erp.articulos.ValoresTablas" metodo="setValorTabla" />

						<campoEntrada name="c"  clase="String" 	metodo="setValorString" />
						<campoEntrada name="d"  clase="Integer" 	metodo="setValorEnter" />
						<campoEntrada name="e"  clase="Double" 	metodo="setValorDoble" />
						<campoEntrada name="f" clase="Boolean" metodo="setValorBoolean" />
						<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
						
					</campoEntrada>
					
				</campoEntrada>
				
				<campoEntrada name="mtEquivalencias" metodo="addEquivalencia" clase="com.jkt.erp.articulos.ProductoEquivUniMed" fieldID="oid_equiv"  >
					<campoEntrada name="oid_unidadOrigen" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedOrigen" />
					<campoEntrada name="oid_unidadDestino" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUniMedDestino" />
					<campoEntrada name="factor" clase="String" metodo="setFactor" />
					<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				</campoEntrada>
				
			</campoEntrada>
		</input>
		
		<forms>
			<form name="FNVar0001"></form>
		</forms>
		
	</operacion>
	
	<!-- TRAER LOS CLASIFICADORES DE UN PRODUCTO -->
	<operacion name="TraerClasifProd" clase="com.jkt.erp.articulos.operaciones.TraerClasifProducto">

		<output name="resultado" tableName="mtClasificadoresProducto">
			<campoSalida value="oid_ClasifProd" target="id" />
			<campoSalida value="DescClasif" target="descripcion" />
		</output>

		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>

		<forms>
			<form name="FNCli0001" />
		</forms>

	</operacion>




<!-- VALIDAR EXISTENCIA SIMPLE-->
	<operacion name="ValidarValores" clase="com.jkt.erp.articulos.operaciones.ValidarValoresDeTablaDeCaracteristicas">
		
		<output name="resultado" tableName="NoSeUsa">
			<campoSalida value="oid" target="id" />
			<campoSalida value="Descripcion" target="descripcion" />
<!-- 			<campoSalida value="Cadena" target="cadena" /> -->
		</output>		
			
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="TUsuario"></form>
		</forms>
		
	</operacion>


</entity>
