<?xml version="1.0" standalone="yes"?>
<!DOCTYPE entity [

  <!ELEMENT entity        (operacion*)>
  <!ELEMENT operacion     (input* , output* , listas? , dataset* , tables*, transformer?, forms)>
<!--   <!ELEMENT operacion     (input* , output* , dataset* , tables*, transformer?, forms)> -->
  
  <!ELEMENT input		  (campoEntrada*)>	<!--   Es la entrada de la operacion. Lo definido aquí llegará en un mapa a la operacion -->
  <!ELEMENT forms		  (form*)>		  	<!--   Para definir una restriccion y conocer que clients utilizan esta operacion. Es a modo de mantenimiento, por ejemplo: al cambiar una operacion, se debe saber quienes suelen llamar a la operacion para realizar los debidos cambios -->
  <!ELEMENT output		  (campoSalida*)> 	<!--   Define el formato de salida -->
  <!ELEMENT transformer	  EMPTY>			<!--   Define una clase que es la encargada de mostrar los resultados en la salida de la operacion. (Muchas tablas, una sola, en paralelo) -->
  
  <!ELEMENT listas		  (lista*)>			<!--   Son las listas para mostrar en la salida-->

  <!ELEMENT lista  (lista*)>  
  <!ATTLIST lista nombreWriter		CDATA    #REQUIRED>
  <!ATTLIST lista nombreLista       CDATA    #REQUIRED>


  <!ELEMENT campoEntrada  (input*|campoEntrada*)>  
  <!ELEMENT campoSalida   (campoSalida*,output*)>  
  
  <!ELEMENT dataset       (campo*)>
  <!ELEMENT campo         EMPTY>
  <!ELEMENT tables       (tableDef+)>
  <!ELEMENT tableDef     (campoTable*)>
  <!ELEMENT campoTable   EMPTY>
  
  <!ATTLIST transformer clase           CDATA #REQUIRED>
  
  <!ATTLIST form name	CDATA #REQUIRED>
  
  <!ATTLIST input name           	 	CDATA    #IMPLIED><!--   Nombre que se corresponde con la entrada de delphi. Si en delphi mandan el valor Name, acá debe exstir en valor Name para obtener los demas datos -->
  <!ATTLIST input keyName           	CDATA    #IMPLIED><!--   Indica el key del mapa que llega a la operacion. Si el valor es 'leo', se debera recuperar usando la key 'leo' sobre el mapa en la operacion -->
  <!ATTLIST input clase           	 	CDATA    #IMPLIED><!-- 	define la clase del parmetro recibido -->
  <!ATTLIST input fieldID           	CDATA    #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
  <!ATTLIST input nombreEntidad        	CDATA    #IMPLIED>
  
  <!ATTLIST campoEntrada name			CDATA #IMPLIED>
  <!ATTLIST campoEntrada clase			CDATA #IMPLIED>
  <!ATTLIST campoEntrada nombreEntidad	CDATA #IMPLIED>
  <!ATTLIST campoEntrada metodo			CDATA #IMPLIED>
  <!ATTLIST campoEntrada fieldID        CDATA #IMPLIED><!--   Define que atributo sera utilizado como id de la entida, esto es para recuperarlo de la base, si acá el valor es UN_ID, en delphi deberian mandar el valor UN_ID -->
 
  <!ATTLIST output name					CDATA #REQUIRED> 
  <!ATTLIST output tableName           	CDATA #REQUIRED><!-- va a representar el nombre de la tabla -->

  <!ATTLIST campoSalida tableName		CDATA #IMPLIED> <!-- en caso de ser hijo de otro campoSalida, es una tabla, y este campo tendra el nombre de la tabla -->
  <!ATTLIST campoSalida target			CDATA #IMPLIED> <!-- El nombre del metodo para recuperar los datos -->
  <!ATTLIST campoSalida value			CDATA #IMPLIED> <!-- el valor de la columna que contendra el valor de resltado de target -->

  <!ATTLIST operacion name              ID    #REQUIRED>
  <!ATTLIST operacion clase             CDATA #IMPLIED>
  <!ATTLIST operacion entidad           CDATA #IMPLIED>
  <!ATTLIST operacion XMLWriter         CDATA #IMPLIED>
  <!ATTLIST operacion redirect          CDATA #IMPLIED>
  <!ATTLIST operacion usaJMS            CDATA #IMPLIED>
  
  <!ATTLIST dataset name                CDATA #REQUIRED>
  <!ATTLIST dataset value               CDATA #IMPLIED>
  <!ATTLIST dataset tabla               CDATA #IMPLIED>
  
  <!ATTLIST campo   name                CDATA #REQUIRED>
  <!ATTLIST campo   value               CDATA #IMPLIED>
  
  <!ATTLIST tableDef    name           	CDATA #REQUIRED>

  <!ATTLIST campoTable	name        	CDATA #REQUIRED>
  <!ATTLIST campoTable  orden       	CDATA #IMPLIED>
  <!ATTLIST campoTable  tipo        	CDATA #IMPLIED>
  <!ATTLIST campoTable  longitud    	CDATA #IMPLIED>
  
]>

<entity>

<!-- 	RECUPERAR LOS CONTACTOS DE UNA SUCURSAL -->
	<operacion name="TraerContactosDeSucursal" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.erp.varios.ClienteSucursal">
		
<!-- 		Esta tabla esta vacia para no crear una nueva clase operaciones.xml. -->
<!-- 		La tabla debe existir en delphi si o si. -->
		
		<output name="resultado" tableName="mtClienteSucursal">
			<campoSalida value="oid_clie_suc" target="id" />
		</output>
		
		<output name="contactos" tableName="mtContactos">
			<campoSalida value="oid_cont_suc" target="id" />
			<campoSalida value="tipo_cont" target="tipoContacto.nombre" />
			<campoSalida value="ape_nom" target="apellidoYNombre" />
			<campoSalida value="email" target="mail" />
<!-- 			<campoSalida value="Cargo" target="tratamiento" /> -->
<!-- 			<campoSalida value="Telefonos" target="telefono" /> -->
<!-- 			<campoSalida value="TelefonoAlt" target="telefonoAlternativo" /> -->
<!-- 			<campoSalida value="Celular" target="celular" /> -->
		</output>

		<listas>
			<lista nombreLista="contactos" nombreWriter="contactos"  />
		</listas>


		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>
		
		<forms>
			<form name="FNVen0003" />
		</forms>		

	</operacion>
	
	
	
	
	<!-- GENERA UN PEDIDO A PARTIR DE UNA COTIZACION. SE DEBERIAN REALIZAR VALIDACIONES COMO QUE LA COTIZACION CUMPLA N CODICIONES CON RESPECTO A SUS CAMPOS -->
	<operacion name="GenerarPedidoUsandoCotizacion" clase="com.jkt.cotizador.operaciones.GenerarPedidoUsandoCotizacion">
	
		<forms>
			<form name="---"></form>
		</forms>

	</operacion>


	<operacion name="GuardarModeloCotizador" clase="com.jkt.cotizador.operaciones.GuardarModeloCotizador">
	
		<input name="mtCab" keyName="modelo" clase="com.jkt.cotizador.dominio.ModeloCotizador" fieldID="oid_mod">
			<campoEntrada>

				<campoEntrada name="cod_mod" clase="String" metodo="setCodigo" />
				<campoEntrada name="des_mod" clase="String" metodo="setDescripcion" />
				<campoEntrada name="Activo" clase="Boolean" metodo="setActivo" />
				
				<campoEntrada name="mtDet" metodo="agregarTituloTransiente" clase="com.jkt.cotizador.dominio.TituloModeloCotizador" fieldID="oid_titu_conc">					
					<campoEntrada name="codInterno" clase="Integer" metodo="setCodigoInterno" />
					<campoEntrada name="codInternoPadre" clase="Integer" metodo="setCodigoInternoPadre" />
					<campoEntrada name="tipo" clase="String" metodo="setTipo" />
					
					<campoEntrada name="cod_titu_conc" clase="String" metodo="setCodigo" />
					<campoEntrada name="des_titu_conc" clase="String" metodo="setDescripcion" />

					<campoEntrada name="oid_conc" clase="com.jkt.cotizador.dominio.ConceptoPresupuesto" metodo="setConcepto" />					
				</campoEntrada>
				
			</campoEntrada>
		</input>
	
		<forms>
			<form name="FNVen0002"></form>
		</forms>

	</operacion>
	
	
	<!-- TRAER UN MODELO DE COTIZADOR, SUS TITULOS Y CONCEPTOS DE PRESUPUESTO -->
	<operacion name="TraerModeloCotizador" clase="com.jkt.cotizador.operaciones.TraerModeloCotizador">

		<output name="modelo" tableName="mtCab">
			<campoSalida value="oid_mod" target="id" />
			<campoSalida value="cod_mod" target="codigo" />
			<campoSalida value="des_mod" target="descripcion" />
		</output>

		<output name="titulos" tableName="mtDet">

			<campoSalida value="oid_titu_conc" target="id" />
			<campoSalida value="oid_mod" target="modeloCotizador.id" />
			<campoSalida value="codInterno" target="codigoInterno" />
			<campoSalida value="codInternoPadre" target="codigoInternoPadre" />
			<campoSalida value="cod_titu_conc" target="codigoReal" />
			<campoSalida value="des_titu_conc" target="descripcionReal" />
			<campoSalida value="tipo" target="tipo" />
			<campoSalida value="oid_conc" target="concepto.id" /> 

		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>

		<forms>
			<form name="---">
			</form>
		</forms>

	</operacion>

	<!-- 	TRAER CONCEPTO DE PRESUPUESTO -->
	<operacion name="TraerConceptoPresupuesto" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.cotizador.dominio.ConceptoPresupuesto">
		
		<output name="resultado" tableName="mtConc">
			<campoSalida value="oid_conc" target="id" />
			<campoSalida value="cod_conc" target="codigo" />
			<campoSalida value="des_conc" target="descripcion" />
			<campoSalida value="pide_art" target="isPideArticulo" />
			<campoSalida value="oid_val_cla" target="componenteValor.id" />
			<campoSalida value="cod_val_cla" target="componenteValor.codigo" />
			<campoSalida value="des_val_cla" target="componenteValor.descripcion" />
			<campoSalida value="oid_mon" target="monedaPorDefecto.id" />
			<campoSalida value="cod_mon" target="monedaPorDefecto.codigo" />
			<campoSalida value="oid_unid_med" target="unidadDeMedidaPorDefecto.id" />
			<campoSalida value="cod_unid_med" target="unidadDeMedidaPorDefecto.codigo" />
		</output>		

		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="FNVen0001" />
		</forms>		

	</operacion>
	
	<!-- GUARDAR CONCEPTO DE PRESUPUESTO -->
	<operacion name="GuardarConceptoPresupuesto" clase="com.jkt.operaciones.GuardarLista">
	
		<input name="mtConc" keyName="objeto" clase="com.jkt.cotizador.dominio.ConceptoPresupuesto" fieldID="oid_conc">
			<campoEntrada>
				<campoEntrada name="cod_conc" clase="String" metodo="setCodigo" />
				<campoEntrada name="des_conc" clase="String" metodo="setDescripcion" />
				<campoEntrada name="pide_art" clase="Boolean" metodo="setPideArticulo" />
				<campoEntrada name="oid_val_cla" clase="com.jkt.varios.dominio.ComponenteValor" metodo="setComponenteValor" />
				<campoEntrada name="oid_mon" clase="com.jkt.varios.dominio.Moneda" metodo="setMonedaPorDefecto" />
				<campoEntrada name="oid_unid_med" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUnidadDeMedidaPorDefecto" />
			</campoEntrada>
		</input>
	
		<forms>
			<form name="FNVen0001"></form>
		</forms>

	</operacion>
	
	
	<!-- GUARDA UNA SOLICITUD DE COTIZACION NUEVA (SIN REVISAR) -->
	<operacion name="GuardarSolicitudCotizacion" clase="com.jkt.operaciones.Guardar">
	
	
		<input name="mtCotizacion" keyName="objeto" clase="com.jkt.dominio.Cotizacion" fieldID="oid_cotiz">
			<campoEntrada>
				<campoEntrada name="fecha" clase="Date" metodo="setFecha" />
				<campoEntrada name="oid_sucu" clase="com.jkt.erp.varios.ClienteSucursal" metodo="setClienteSucursal" />
				<campoEntrada name="oid_vend" clase="com.jkt.erp.varios.Vendedor" metodo="setVendedor" />
				<campoEntrada name="oid_repre" clase="com.jkt.erp.varios.Representante" metodo="setRepresentante" />

				<campoEntrada name="fecha_vencimiento" clase="Date" metodo="setFechaVencimiento" />
				<campoEntrada name="referencia" clase="String" metodo="setReferencia" />
				<campoEntrada name="oid_cont_suc" clase="com.jkt.varios.dominio.Contacto" metodo="setContactoReferencia" />

<!-- 				<campoEntrada name="oid_condicionPago" clase="com.jkt.varios.dominio.CondPago" metodo="setCondicionPago" /> -->
				
<!-- 				<campoEntrada name="comportamiento" clase="String" metodo="setComportamiento" /> -->
<!-- 				<campoEntrada name="lugarEmision" clase="String" metodo="setLugarEmision" /> -->
<!-- 				<campoEntrada name="anulado" clase="Boolean" metodo="setAnulado" /> -->
<!-- 				<campoEntrada name="tipoComprobante" clase="com.jkt.dominio.TipoComprobante" metodo="setTipoComprobante" /> -->
<!-- 				<campoEntrada name="letra" clase="Char" metodo="setLetra" /> -->

<!-- 				<campoEntrada name="respCargaClie" clase="Boolean" metodo="setCargaACargoDeCliente" /> -->
<!-- 				<campoEntrada name="respTranspClie" clase="Boolean" metodo="setTransporteACargoDeCliente" /> -->
<!-- 				<campoEntrada name="respDescargaClie" clase="Boolean" metodo="setDescargaACargoDeCliente" /> -->

				
				<campoEntrada name="mtItems" metodo="agregarDetalle" clase="com.jkt.dominio.CotizacionDet" fieldID="oid_item">
					<campoEntrada name="oid_art" clase="com.jkt.erp.articulos.Producto" metodo="setProducto" />
					<campoEntrada name="cant" clase="Integer" metodo="setCantidad" />
					<campoEntrada name="detalle" clase="String" metodo="setDescripcion" />
					<campoEntrada name="oid_tipo" clase="Integer" metodo="setTipoVenta" />
					<campoEntrada name="referencia" clase="String" metodo="setReferencia" />
					
<!-- 					<campoEntrada name="oid_unidadMedida" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUnidadMedida" /> -->
<!-- 					<campoEntrada name="precio" clase="Double" metodo="setPrecio" /> -->
<!-- 					<campoEntrada name="moneda" clase="com.jkt.varios.dominio.Moneda" metodo="setMoneda" /> -->
<!-- 					<campoEntrada name="oid_cotizador" clase="com.jkt.cotizador.dominio.Cotizador" metodo="setCotizador" /> -->
				</campoEntrada>
				
				<campoEntrada name="mtArchivos" metodo="agregarEspecificacion" clase="com.jkt.varios.dominio.Especificacion" fieldID="oid_arch">
					<campoEntrada name="archivo" clase="String" metodo="setNombreCompleto" />
					<campoEntrada name="oid_usu" clase="Integer" metodo="setIdentificadorDeUsuario" />
					<campoEntrada name="comentario" clase="String" metodo="setComentario" />
				</campoEntrada>
				
			</campoEntrada>
		</input>
	
		<forms>
			<form name="-"></form>
		</forms>

	</operacion>
	
	<!-- TRAE UNA SOLICITUD FILTRANDOLA POR ID -->
	<operacion name="TraerSolicitudCotizacion" clase="com.jkt.cotizador.operaciones.TraerCotizacion" >

		<output name="cotizaciones" tableName="mtCotizacion">

			<campoSalida value="oid_cotiz" target="id" />
			<campoSalida value="nro_cotiz" target="nro" />
			<campoSalida value="fecha" target="fecha" />
			
			<campoSalida value="oid_sucu" target="clienteSucursal.id" />
			<campoSalida value="nro_sucu" target="clienteSucursal.numero"/>
			<campoSalida value="des_sucu" target="clienteSucursal.descripcionCompleta" />

			<campoSalida value="oid_clie" target="clienteSucursal.cliente.id" />
			<campoSalida value="cod_clie" target="clienteSucursal.cliente.codigo" />
			<campoSalida value="razonSocial" target="clienteSucursal.cliente.sujetoImpositivo.razonSocial" />

			<campoSalida value="oid_vend" target="vendedor.id" />
			<campoSalida value="cod_vend" target="vendedor.codigo" />
			<campoSalida value="des_vend" target="vendedor.descripcion" />
			
			<campoSalida value="oid_repre" target="representante.id" />
			<campoSalida value="cod_repre" target="representante.codigo" />
			<campoSalida value="des_repre" target="representante.descripcion" />
			
			<campoSalida value="referencia" target="referencia" />
			<campoSalida value="fecha_vencimiento" target="fechaVencimiento" />
			<campoSalida value="oid_cont_suc" target="contactoReferencia.id" />
			
			
<!-- 			<campoSalida value="respCargaEmpr" target="isCargaACargoDeEmpresa" /> -->
<!-- 			<campoSalida value="respCargaClie" target="isCargaACargoDeCliente" /> -->
			
<!-- 			<campoSalida value="respTranspEmpr" target="isTransporteACargoDeEmpresa" /> -->
<!-- 			<campoSalida value="respTranspClie" target="isTransporteACargoDeCliente" /> -->
			
<!-- 			<campoSalida value="respDescargaEmpr" target="isDescargaACargoDeEmpresa" /> -->
<!-- 			<campoSalida value="respDescargaClie" target="isDescargaACargoDeCliente" /> -->

		</output>
		
		<output name="detalles" tableName="mtItems">
			<campoSalida value="oid_item" target="id" />
			<campoSalida value="oid_cotiz" target="comprobanteVenta.id" />

			<campoSalida value="oid_art" target="producto.id" />
			<campoSalida value="cod_art" target="producto.codigo" />
			<campoSalida value="des_abrev_art" target="producto.descripcionAbrev" />

			<campoSalida value="referencia" target="referencia" />

			<campoSalida value="cant" target="cantidad" />
			
			<campoSalida value="oid_tipo" target="tipoVenta" />

			<campoSalida value="detalle" target="descripcion" />
		</output>

		<output name="archivos" tableName="mtArchivos">
			<campoSalida value="oid_arch" target="id" />
			<!-- <campoSalida value="oid_cotiz" target="CAMPOTRANSIENTE" /> -->
			<campoSalida value="fecha_subida" target="fechaDeSubidaPlana" />
			<campoSalida value="oid_usu" target="identificadorDeUsuario" />
			<campoSalida value="usuario" target="nombreUsuario" />
			<campoSalida value="comentario" target="comentario" />
			<campoSalida value="archivo" target="nombreCompleto" />
		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer" />
		
		<forms>
			<form name="---"></form>
		</forms>		

	</operacion>
	
	<!-- TRAER LOS TIPOS DE VENTA DISPONIBLES -->
	<operacion name="TraerTiposDeVenta" clase="com.jkt.cotizador.operaciones.TraerTiposDeVenta">
										
		<output name="entidades" tableName="mtTiposVenta">
			<campoSalida value="oid_tipo" target="codigo" />
			<campoSalida value="des_tipo" target="descripcion" />
		</output>
						
		<transformer clase="com.jkt.transformers.SimpleTransformer"></transformer>
		
		<forms>
			<form name="FNCla0001"> </form>
		</forms>
		
	</operacion>
	
	
	
	<!-- TRAE TODOS LOS ITEMS DE COTIZACIONES CON ESTADO PENDIENTE DE COTIZAR-->
	<operacion name="TraerItemsACotizar" clase="com.jkt.cotizador.operaciones.TraerItemsParaCotizar" >

		<output name="items" tableName="mtItems">
<!-- 			<campoSalida value="oid_cotiz" target="comprobanteVenta.id" /> -->
			<campoSalida value="oid_item" target="id" />
			<campoSalida value="nro_cotiz" target="comprobanteVenta.nro" />
			<campoSalida value="fecha" target="comprobanteVenta.fecha" />
			<campoSalida value="des_clie_sucu" target="comprobanteVenta.clienteSucursal.descripcion" />
			<campoSalida value="des_vend" target="comprobanteVenta.vendedor.descripcion" />
			<campoSalida value="nro_item" target="numero" />
			<campoSalida value="cant" target="cantidad" />
			<campoSalida value="detalle" target="descripcion" />
		</output>
		
		<transformer clase="com.jkt.transformers.SimpleTransformer" />
		
		<forms>
			<form name="FNVen0004"> </form>
		</forms>		

	</operacion>


	<!-- TRAE TODOS LOS ITEMS DE COTIZACIONES CON ESTADO PENDIENTE DE COTIZAR-->
	<operacion name="HelpTraerItemsDePresupuesto" clase="com.jkt.cotizador.operaciones.TraerItemsParaCotizar" >

		<output name="items" tableName="mtInput">
<!-- 			<campoSalida value="oid_cotiz" target="comprobanteVenta.id" /> -->
			<campoSalida value="oid" target="id" />

<!-- 			RETORNA LOS DATOS DEL ESTADO DEL ITEM -->
			<campoSalida value="codigo" target="estadoId" />
			<campoSalida value="des_estado" target="descripcionEstado" /> 
			
<!-- 			 VER ESTO CON SANTI. Este 'codigo' sería el 'oid' del estado. Yo llamo a una operacion o a otra en la vista dependiendo de este valor.			 -->
			
			
			<campoSalida value="descripcion" target="comprobanteVenta.clienteSucursal.descripcion" />
			<campoSalida value="nro_cotiz" target="comprobanteVenta.nro" />
			<campoSalida value="fecha" target="comprobanteVenta.fecha" />
			
<!-- 			VER ESTO CON SANTI. ¿Puede ser que el 'item' no tenga Estado pero sí la Cotizacion global??? -->
<!-- 																		   Según tengo entendido (quizás esté mal), LOS ITEMS tienen el estado 'Pendiente de Cotizar', -->
<!-- 																		   'Cotizado pero No Autorizado', 'Autorizado', 'Rechazado', etc; Mientras que la Cotizacion,  -->
<!-- 																		   quien tiene una lista de estos items, tendrá otros estados o similares... ¿qué opinás? -->
			
			
			<campoSalida value="des_vend" target="comprobanteVenta.vendedor.descripcion" />
			<campoSalida value="nro_item" target="numero" />
			<campoSalida value="cant" target="cantidad" />
			<campoSalida value="detalle" target="descripcion" />
		</output>
		
		<transformer clase="com.jkt.transformers.SimpleTransformer" />
		
		<forms>
			<form name="FNHlp0001"> </form>
		</forms>		

	</operacion>


	<!-- TRAE UN ITEM SELECCIONADO DESDE LA LISTA DE ITEMS DE COTIZACIONES CON ESTADO PENDIENTE DE COTIZAR -->
	<operacion name="TraerCotizacionDelItem" clase="com.jkt.operaciones.TraerCotizacionDelItem" >
<!-- 	<operacion name="TraerCotizacionDelItem" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.dominio.ComprobanteVentaDet"> -->

		<output name="item" tableName="mtItem">
			<campoSalida value="oid_item" target="id" />
			<campoSalida value="nro_cotiz" target="comprobanteVenta.nro" /> <!-- PRESUPUESTO -->
			<campoSalida value="fecha" target="comprobanteVenta.fecha" />
			<campoSalida value="des_clie_sucu" target="descClieSucu" />			
			<campoSalida value="des_vend" target="comprobanteVenta.vendedor.descripcion" />
			<campoSalida value="cod_estado" target="estadoId" />
			<campoSalida value="des_tipo_item" target="descripcionTipoDeVenta" />
			<campoSalida value="detalle_item" target="descripcion" />
			<campoSalida value="cod_art" target="producto.codigo" />
			<campoSalida value="des_abrev_art" target="producto.descripcionAbrev" />	
		</output>

		<output name="titulos" tableName="mtDetCotiz">
<!-- 			<campoSalida value="oid_det" target="id" /> -->
			<campoSalida value="oid_det" target="identificadorDetalle" />
<!-- 			<campoSalida value="oid_mod" target="modeloCotizador.id" /> -->
			<campoSalida value="codInterno" target="codigoInterno" />
			<campoSalida value="codInternoPadre" target="codigoInternoPadre" />
			
			<campoSalida value="oid_titu_conc" target="id" />
			<campoSalida value="cod_titu_conc" target="codigoReal" />
			<campoSalida value="des_titu_conc" target="descripcionReal" />
			<campoSalida value="tipo" target="tipo" />
			<campoSalida value="oid_conc" target="concepto.id" />
		
			<campoSalida value="cant" target="detalleDeConcepto.cantidad" />
			
			<campoSalida value="importe_unit" target="precio" />
			<campoSalida value="oid_moneda" target="moneda.id" />
			<campoSalida value="fecha_costo" target="fechaPrecioCosto" />
			<campoSalida value="importe_total_3" target="detalleDeConcepto.importeVenta" />
			
			<campoSalida value="markup" target="detalleDeConcepto.markUp" />

			<campoSalida value="oid_unid_med" target="concepto.unidadDeMedidaPorDefecto.id" />
			<campoSalida value="cod_unid_med" target="concepto.unidadDeMedidaPorDefecto.codigo" />
			
<!-- 			Si el titulo pide articulo, se mostraran por cada titulo, que seria concepto, un producto separado por cada producto que tenga asignado el valor q se corresponde con el concepto. NO SE ENTIENDE MUCHO, EXPLICAR MEJOR... TODO -->
			<campoSalida value="oid_art" target="producto.id" />
			<campoSalida value="des_art" target="producto.descripcionAbrev" />
		</output>
		
		<output name="cotizador" tableName="mtCabCotiz">
		
			<campoSalida value="oid_cotiz" target="id" />
			
			<campoSalida value="oid_mod" target="modelo.id" />
			<campoSalida value="cod_mod" target="modelo.codigo" />
			<campoSalida value="des_mod" target="modelo.descripcion" />

			<campoSalida value="oid_moneda_expresada" target="monedaExpresada.id" />
			
		</output>
		
		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer" />
		
		<forms>
			<form name="FNVen0005"></form>
		</forms>

	</operacion>


	<!-- TRAE UN ITEM SELECCIONADO DESDE LA LISTA DE ITEMS DE COTIZACIONES CON ESTADO PENDIENTE DE COTIZAR -->
	<operacion name="TraerItem" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.dominio.CotizacionDet">

		<output name="resultado" tableName="mtItem">
			<campoSalida value="oid_item" target="id" />
			<campoSalida value="nro_cotiz" target="comprobanteVenta.nro" /> <!-- PRESUPUESTO -->
			<campoSalida value="fecha" target="comprobanteVenta.fecha" />
			<campoSalida value="des_clie_sucu" target="descClieSucu" />			
<!-- 			<campoSalida value="cod_clie" target="comprobanteVenta.clienteSucursal.cliente.codigo" /> -->
<!-- 			<campoSalida value="razonSocial" target="comprobanteVenta.clienteSucursal.cliente.sujetoImpositivo.razonSocial" /> -->
			<campoSalida value="des_vend" target="comprobanteVenta.vendedor.descripcion" />
			<campoSalida value="des_tipo_item" target="descripcionTipoDeVenta" />
			<campoSalida value="detalle_item" target="descripcion" />
			<campoSalida value="cod_art" target="producto.codigo" />
			<campoSalida value="des_abrev_art" target="producto.descripcionAbrev" />			
		
			<!-- 			RETORNA LOS DATOS DEL ESTADO DEL ITEM -->
			<campoSalida value="cod_estado" target="estadoId" />
<!-- 			<campoSalida value="des_estado" target="descripcionEstado" />  -->
			
		</output>
		
		<transformer clase="com.jkt.transformers.SimpleTransformer" />
		
		<forms>
			<form name="FNVen0005"></form>
		</forms>

	</operacion>
	
	
	<!-- CONFIGURACION DEL COTIZADOR. ESTA OPERACION SE EJECUTA AL MOMENTO DE GUARDAR EN EL COTIZADOR LA RELACION CON UN MODELO Y SUS CORRESPONDIENTES RELACIONES. -->
	<operacion name="ConfigurarCotizador" clase="com.jkt.operaciones.GuardarLista">
	
		<input name="mtCabCotiz" keyName="objeto" clase="com.jkt.cotizador.dominio.Cotizador" fieldID="oid_cotiz">
			<campoEntrada>
			
<!-- 				<campoEntrada name="revisado" clase="Boolean" metodo="setRevisado" /> -->
<!-- 				<campoEntrada name="usuarioRevision" clase="String" metodo="setUsuarioRevision" /> -->
<!-- 				<campoEntrada name="fechaRevision" clase="Date" metodo="setFechaRevision" /> -->
				<campoEntrada name="oid_mod" clase="com.jkt.cotizador.dominio.ModeloCotizador" metodo="setModelo" />
				<campoEntrada name="oid_moneda_expresada" clase="com.jkt.varios.dominio.Moneda" metodo="setMonedaExpresada" />
<!-- 				<campoEntrada name="autorizado" clase="boolean" metodo="setAutorizado" /> -->
				
				<!-- ES PRIMORDIAL EL ORDEN DE ESTOS DOS CAMPOS, YA QUE EL CODIGO DE ESTADO NECESITA QUE EXISTA UN ITEM ASIGNADO -->
				<campoEntrada name="oid_item" clase="com.jkt.dominio.CotizacionDet" metodo="setItem" />
				<campoEntrada name="cod_estado" clase="String" metodo="setCodigoEstado" />

				<campoEntrada name="mtDetCotiz" metodo="agregarDetalle" clase="com.jkt.cotizador.dominio.CotizadorDet" fieldID="oid_det">
					<campoEntrada name="oid_conc" clase="com.jkt.cotizador.dominio.ConceptoPresupuesto" metodo="setConceptoPresupuesto" />
					<campoEntrada name="oid_art" clase="com.jkt.erp.articulos.Producto" metodo="setProducto" />
					<campoEntrada name="cant" clase="Double" metodo="setCantidad" />
					<campoEntrada name="oid_unid_med" clase="com.jkt.varios.dominio.UnidadMedida" metodo="setUnidadMedida" />
					<campoEntrada name="importe_unit" clase="Double" metodo="setPrecioUnitario" />
					<campoEntrada name="importe_total_3" clase="Double" metodo="setImporteVenta" />
					<campoEntrada name="markup" clase="Double" metodo="setMarkUp" />
					<campoEntrada name="oid_moneda" clase="com.jkt.varios.dominio.Moneda" metodo="setMoneda" />
					<campoEntrada name="oid_titu_conc" clase="com.jkt.cotizador.dominio.TituloModeloCotizador" metodo="setTituloModeloCotizador" />
					
<!-- 					<campoEntrada name="importe_total" clase="" metodo="" /> -->
<!-- 					<campoEntrada name="importe_total_2" clase="" metodo="" /> -->
<!-- 					<campoEntrada name="cotizacion" clase="Double" metodo="setCotizacion" /> -->
				</campoEntrada>
			</campoEntrada>
		</input>
		
		<forms>
			<form name="FNVen0005"></form>
		</forms>

	</operacion>
	
	<!-- TRAER UN MODELO DE COTIZADOR, SUS TITULOS Y CONCEPTOS DE PRESUPUESTO -->
	<operacion name="TraerModeloParaCotizar" clase="com.jkt.cotizador.operaciones.TraerModeloParaCotizar">

<!-- 		<output name="modelo" tableName="mtCabCotiz"> -->
<!-- 			<campoSalida value="oid_mod" target="id" /> -->
<!-- 			<campoSalida value="cod_mod" target="codigo" /> -->
<!-- 			<campoSalida value="des_mod" target="descripcion" /> -->
<!-- 		</output> -->

		<output name="titulos" tableName="mtDetCotiz">
			<campoSalida value="oid_det" target="identificadorDetalle" />
<!-- 			<campoSalida value="oid_mod" target="modeloCotizador.id" /> -->
			<campoSalida value="codInterno" target="codigoInterno" />
			<campoSalida value="codInternoPadre" target="codigoInternoPadre" />
			
			
			<campoSalida value="oid_titu_conc" target="id" />
			<campoSalida value="cod_titu_conc" target="codigoReal" />
			<campoSalida value="des_titu_conc" target="descripcionReal" />
			<campoSalida value="tipo" target="tipo" />
			<campoSalida value="oid_conc" target="concepto.id" />
		
		
<!-- 			<campoSalida value="oid_moneda" target="concepto.monedaPorDefecto.id" /> -->
			<campoSalida value="oid_moneda" target="moneda.id" />
			
			<campoSalida value="fecha_costo" target="fechaPrecioCosto" />
			<campoSalida value="importe_unit" target="precio" />
			
			
			
			<campoSalida value="oid_unid_med" target="concepto.unidadDeMedidaPorDefecto.id" />
			<campoSalida value="cod_unid_med" target="concepto.unidadDeMedidaPorDefecto.codigo" />
			
			
			<!-- Si el titulo pide articulo, se mostraran por cada titulo, que seria concepto, un producto separado por cada producto que tenga asignado el valor q se corresponde con el concepto. NO SE ENTIENDE MUCHO, EXPLICAR MEJOR... TODO -->
			<campoSalida value="oid_art" target="producto.id" />
			<campoSalida value="des_art" target="producto.descripcionAbrev" />
		</output>

		<transformer clase="com.jkt.transformers.ParalelResponseListenerTransformer"></transformer>

		<forms>
			<form name="FNVen0005">
			</form>
		</forms>

	</operacion>
	
	
<!-- 	OPERACIONES BASICAS DE UNA PLANTILLA DE TEXTO -->
<!-- 	TRAER CONCEPTO DE PRESUPUESTO -->
	<operacion name="TraerPlantillas" clase="com.jkt.operaciones.TraerEntidades" entidad="com.jkt.dominio.Plantilla">
		
		<output name="resultado" tableName="mtInput">
			<campoSalida value="oid_plan" target="id" />
			<campoSalida value="cod_plan" target="codigo" />
			<campoSalida value="plantilla" target="descripcion" />
			<campoSalida value="descr_plan" target="plantilla" />
			<campoSalida value="Activo" target="isActivo" />
		</output>		
